development:
  adapter: postgresql
  encoding: utf8 
  database: myanmardealer_db 
  pool: 5
  password: root


production: 
   adapter: postgresql
   encoding: utf8 
   database: myanmardealer_db 



