development:
  adapter: postgresql
  encoding: utf8 
  database: dealer_db 
  pool: 5
  password: root


production: 
   adapter: postgresql
   encoding: utf8 
   database: dealer_db 
   pool: 10 
   username: htoo 
   password: root 
   reconnect: true